<?php
include(__DIR__.'/../config/config.php');
include(__DIR__.'/../config/password.php');
include(__DIR__.'/../config/fonctions.php');
//tickers
include(__DIR__.'/../tests/tickers.php');
//classes
include(__DIR__.'/../classes/db.class.php');
include(__DIR__.'/../classes/gamemaster.class.php');
//include(__DIR__.'/../classes/bcrypt.class.php');
include(__DIR__.'/../classes/user.class.php');
include(__DIR__.'/../classes/waitings.class.php');
include(__DIR__.'/../classes/stock.class.php');
include(__DIR__.'/../classes/transaction.class.php');
include(__DIR__.'/../classes/yql_request.class.php');
include(__DIR__.'/../classes/trader.class.php');
include(__DIR__.'/../classes/broker.class.php');
include(__DIR__.'/../classes/market.class.php');
include(__DIR__.'/../classes/firm.class.php');
//cron
//include('config/cron.php');